// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCartAPI.Models;

namespace MyCartAPI.Migrations
{
    [DbContext(typeof(CartDetailContext))]
    [Migration("20210210140522_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("MyCartAPI.Models.CartDetail", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CodeProduct")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NameProduct")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PriceProduct")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdProduct");

                    b.ToTable("CartDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
